baseURL = 'https://americastapestry.netlify.app/'
languageCode = 'en-us'
title = "America's Tapestry"
copyright = "Stefan Romero Design 2025"
cleanDestinationDir = true

[params]
name = 'Stefan Romero Design'

[params.staticman]
endpoint = "https://americastapestry.netlify.app/v2/entry"
username = "your_username"
repository = "your_blog_repo"
branch = "master"
